name: Label-Based PR Merge

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'merge'
    steps:
      - uses: victoriacheng15hub/platform-actions/merge-on-label@main
        with:
          pr_url: ${{ github.event.pull_request.html_url }}
          label: merge
          token: ${{ secrets.GITHUB_TOKEN }}