name: Label-Based PR Merge

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'merge'
    steps:
      - name: Remove the trigger label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit "${{ github.event.pull_request.html_url }}" --remove-label "merge"

      - name: Enable auto-merge for labeled PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --squash --delete-branch "${{ github.event.pull_request.html_url }}"