name: Publish Post

on:
  schedule:
    - cron: "30 0 * * 2"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      AUTHOR_NAME: 'github-actions[bot]'
      AUTHOR_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Publish Post Script
        env:
          GH_TOKEN: ${{ secrets.SYNC_BLOG_TOKEN }}
        run: ./scripts/publish_blog_post.sh
