name: Publish Post

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Generate Unique Branch Name
        id: branch-name
        run: |
          echo "branch_name=publish-post-$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Create and switch to publish-post branch
        run: git switch -c "${{ steps.branch-name.outputs.branch_name }}"

      - name: Run Publish Post Script
        run: npm run publish

      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code; then
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Exist if no changes
        if: steps.changes.outputs.changes_detected == 'false'
        run: exit 0

      - name: Git Config
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Commit changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git add src/content/
          git commit -m "chore: the post is published! 🎉"
          git push origin HEAD:refs/heads/"${{ steps.branch-name.outputs.branch_name }}"

      - name: Create PR
        if: steps.changes.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base main \
            --head "${{ steps.branch-name.outputs.branch_name }}" \
            --title "Publish Post: automated PR" \
            --body "Auto-generated by GitHub Actions"
