name: Publish Post

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Create and switch to publish-post branch
        run: git switch -c publish-post || git switch publish-post

      - name: Run Publish Post Script
        run: npm run publish

      - name: Check for changes
        id: changes
        run: |
          if git diff --exit-code; then
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Exist if no changes
        if: steps.changes.outputs.changes_detected == 'false'
        run: exit 0

      - name: Git Config
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Commit changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git add src/content/
          git commit -m "chore: the post is published! 🎉"
          git pull origin publish-post --rebase
          git push -u origin HEAD

      - name: Create PR
        if: steps.changes.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base=main --head=publish-post -f
