name: Publish Post

on:
  schedule:
    - cron: "30 0 * * 2"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Publish Post Script
        id: publish_script
        run: ./scripts/publish_blog_post.sh

      # The 'changed' and 'post_title' outputs are set dynamically inside ./scripts/publish_blog_post.sh
      - name: Commit and open pull request
        if: steps.publish_script.outputs.changed == 'true'
        uses: ./.github/actions/commit-and-pr
        with:
          path: blog/
          branch_prefix: publish-post
          commit_message: "chore: publish post ${{ steps.publish_script.outputs.post_title }} ! 🎉"
          pr_title: "Publish Post: ${{ steps.publish_script.outputs.post_title }}"
          pr_body: "This publishes the post titled **${{ steps.publish_script.outputs.post_title }}**. 🎉"
          github_token: ${{ secrets.GITHUB_TOKEN }}
